In [2]:
from sklearn.pipeline import Pipeline

# feature scaling
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [7]:
steps = [("standard_scaler", StandardScaler()),
        ("Classifier", LogisticRegression())]

In [8]:
steps

[('standard_scaler', StandardScaler()), ('Classifier', LogisticRegression())]

In [9]:
Pipeline(steps)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [13]:
pipe = Pipeline(steps)

In [10]:
# lets create our own dataset
from sklearn.datasets import make_classification
X, y = make_classification(n_samples = 1000)

In [11]:
X.shape

(1000, 20)

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [15]:
X_train

array([[-0.89408652, -0.05279413, -0.03527102, ..., -0.60665268,
        -1.02317822, -0.5864398 ],
       [ 0.83658249,  0.46554841,  0.85643648, ..., -1.88893804,
         0.60995666, -0.18859358],
       [-0.56658668,  0.78172339,  0.78758271, ..., -0.81710147,
        -1.73410839, -2.02871434],
       ...,
       [-0.10606507,  0.32537537,  0.66685961, ..., -2.3271978 ,
        -0.9007081 , -1.94564668],
       [-1.31804704,  0.06693785, -0.64957684, ...,  0.59936704,
        -0.39330177,  0.50359362],
       [-1.82229966, -2.87105536, -0.01806328, ..., -1.54918349,
        -0.02761171, -1.41178712]], shape=(670, 20))

In [16]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [17]:
y_pred = pipe.predict(X_test)

In [18]:
y_pred

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,

## EXAMPLE- 2
Displaying a pipeline with standard scaler, dimensionality reduction and then estimator

In [19]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [20]:
steps = [("scaling", StandardScaler()),
        ("PCA", PCA(n_components = 3)),
        ("SVC", SVC())]

In [22]:
Pipeline(steps)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [23]:
pipe2 = Pipeline(steps)

In [25]:
pipe2.fit(X_train, y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [26]:
pipe2.predict(X_test)

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,

## EXAMPLE-3
Complex ex of columns transformer

In [27]:
from sklearn.impute import SimpleImputer

In [28]:
# numerical processing pipeline
import numpy as np
numeric_processor = Pipeline(
    steps = [("imputation_mean", SimpleImputer(missing_values = np.nan, strategy = "mean")),
            ("scaler", StandardScaler())]
)

In [29]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [31]:
# categorical processing pipeline
from sklearn.preprocessing import OneHotEncoder
categorical_processor = Pipeline(
    steps = [("imputation_constant", SimpleImputer(fill_value = "missing", strategy = "constant")),
            ("onehot", OneHotEncoder(handle_unknown = "ignore"))]
)

In [32]:
categorical_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [34]:
# combining processing techniques
from sklearn.compose import ColumnTransformer

In [35]:
preprocessor = ColumnTransformer(
    [("categorical", categorical_processor, ["gender", "City"]),
    ("numerical", numeric_processor, ["age", "height"])]
)

In [36]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [37]:
from sklearn.pipeline import make_pipeline

In [38]:
make_pipeline(preprocessor, LogisticRegression())

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])